# Server Configuration
server.port=8081

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phantienthinh0909@gmail.com
spring.mail.password=raqikustsplewoop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Email recipient (your email - where contact messages will be sent)
contact.email.to=phantienthinh0909@gmail.com
